name: extapi

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run style check
        run: uv run ruff format --check --diff extapi tests

      - name: Run ruff
        run: uv run ruff check extapi tests

      - name: Run mypy
        run: uv run mypy --enable-error-code ignore-without-code extapi tests

      - name: Run deptry
        run: uv run deptry . -e 'env|\.env|venv|\.venv|\..+'

      - name: Run tests
        run: uv run pytest .

  publish:
    name: Publish to PyPI
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - run: echo "Current tag is ${{ steps.get_tag.outputs.TAG }}"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      - name: Publish dist
        run: |
          python -m build . -s
          tree dist
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ steps.get_tag.outputs.TAG }}
          files: |
            dist/*
